### ISSUE TITLE
Why isn't pipe read happening in a separate thread?

### ISSUE THREAD

**Issue by sidkshatriya** [charlesetc/feather#24]
Thanks for this useful and cool library in OCaml! I had a question about the code. I am not able to figure out why it should work for large pipe writes. See my comments within the below code excerpt...

Sorry if I'm missing something...

```ocaml
(* Launch the command and collect expected channels *)
let collect (type a) ?cwd ?env (what_to_collect : a what_to_collect) cmd : a =
  let eval ?(stdout_writer = Unix.dup Unix.stdout)
      ?(stderr_writer = Unix.dup Unix.stderr) () =
    eval cmd
      {
        stdin_reader = Unix.dup Unix.stdin;
        stdout_writer;
        stderr_writer;
        cwd;
        env;
      }
  in

  match what_to_collect with
  | Collect_status -> eval ()
  | Collect_stdout ->
      let stdout_reader, stdout_writer = Unix.pipe () in
(***The eval invocation is blocking. We don't move to next statement until program ends. The program will write to the write side of the pipe i.e. the stdout_writer.*)
(* If write is smaller than pipe capacity the program will be able to end properly. However if write is larger than pipe capacity *) 
(* then program will block until the reader side reads the data in the pipe. But reader side will only read once this program ends! Potential for hang??! *)
      let (_ : int) = eval ~stdout_writer () in
 (*** We are reading from pipe here *)
      let stdout = collect_into_string stdout_reader in
      stdout
````

In Linux and other Unixes, each pipe has a write capacity. If you exceed the capacity of the pipe, your write to the pipe will block until the reader side reads. I notice that your `collect_into_string` is only running after the program has already run. So `Collect_stdout` code should hang for large writes to the pipe.

In Linux pipe capacity by default is 64K bytes (See https://man7.org/linux/man-pages/man7/pipe.7.html ).

Again, I apologize if I'm missing something here...

**Comment by Firobe** [comment]
Hello!
With your assumptions, there should indeed be a problem for large writes. However, what I think you are missing is that in the context of pipes, each program (in fact each `eval` call) is actually running in a separate thread !

https://github.com/charlesetc/feather/blob/c3c854db26b137a09a7c8ad45a1463300fa663c8/src/feather.ml#L235

**Comment by sidkshatriya** [comment]
Yes, I've seen that. For `Pipe (a, b)` (which is of type `cmd`) each end of the pipe is run in a separate thread. However I don't think this is applicable. In my view the problem still remains.

In the code which I posted above:
```ocaml
| Collect_stdout ->
      (**** Note Unix.pipe ***)
      let stdout_reader, stdout_writer = Unix.pipe () in
      let (_ : int) = eval ~stdout_writer () in
      let stdout = collect_into_string stdout_reader in
      stdout
```
This is a call to plain `Unix.pipe` and is not related here to `Pipe` which you refer to.

I have found a way to hang feather on Linux where the default pipe capacity is 64K (65536 bytes)
```bash
$ opam install utop
$ dd if=/dev/zero of=/some/path/wont_hang bs=64K count=1
$ dd if=/dev/zero of=/some/path/will_hang bs=65K count=1
$ dune utop
```

Here is what the utop session looks like in brief
```
# #require "feather";;
# open Feather;;
# collect stdout @@ process "cat" [ "/some/path/wont_hang" ];;
<<< WORKS >>>  
# collect stdout @@ process "cat" [ "/some/path/will_hang" ];;  
<<< HANGS >>>
```

**Comment by sidkshatriya** [comment]
P.S. You can also choose arbitrary files on your computer and don't need to use `dd` as I did in my example. Files below 64K will work and those above 64K will hang.

**Comment by sidkshatriya** [comment]
@charlesetc Was wondering if you had a look at the above reproducer ^^

**Comment by charlesetc** [comment]
Hiya! I can verify this is a bug. (Though I need to use a lowercase 'k' in the dd commands on mac.) Thank you for finding and reporting it!

I don't have time to work on this at the moment but I'm happy to review a pull request if you or anyone else wants to take a shot at fixing it!

**Comment by Firobe** [comment]
Sorry @sidkshatriya I misunderstood the issue at first. I made a PR (https://github.com/charlesetc/feather/pull/25) that suggests a fix.
