### ISSUE TITLE
Implicit dependency on procps (pgrep)

### ISSUE THREAD

**Issue by balsoft** [charlesetc/feather#26]
Feather [calls pgrep](https://github.com/charlesetc/feather/blob/dcbcf9e6406178a40d41982cc3e0f7e9395e8ba3/src/feather.ml#L633), which is part of procps package on Debian and many other Linux distributions, and is not necessarily present on the system. Would you consider adding a relevant depext?

**Comment by charlesetc** [comment]
Good call! Yes that seems like a good solution. PRs are welcome, but if people are busy I should be able to get to it in a couple of weeks!

**Comment by balsoft** [comment]
Thank you for such a swift response! I'll make a PR shortly.
