### ISSUE TITLE
Unix.EINTR in utop running any command

### ISSUE THREAD

**Issue by charlesetc** [charlesetc/feather#7]
I am pretty sure this got introduced when switching from Core to Base. But it only appears when running in utop, as far as I can tell. Compiling with byte mode also does not trigger it. I don't understand why this error is happening... It could be that the waitpid function from Core_unix is what was preventing it from before. If adding core_unix increases our start-up time too much, I might just want to copy the wait_pid function into feather.

```ocaml
utop # ls "." |> collect_lines;;
Exception: Unix.Unix_error(Unix.EINTR, "waitpid", "")
Raised by primitive operation at unknown location
Called from unknown location
Called from unknown location
Called from unknown location
Called from unknown location
Called from unknown location
```

**Comment by tmarti2** [comment]
This command works fine for me :thinking:

**Comment by Firobe** [comment]
It works for me also. I don't know what might be triggering this. The only lead I have is that from transitioning from Core to Base, the `Thread.create` lost its `~on_uncaught_exn:Kill_whole_process` parameter and the default for OCaml is to just print the backtrace.

However, I don't know why there would be an exception in the first place or if it's even related.

**Comment by charlesetc** [comment]
That's nice to hear! If it's just me so far and just in utop, it's a pretty uncommon bug at least. I'll do some experimentation sometime to try to see what's going on.

**Comment by juxd** [comment]
Hello, I did a bit of looking around in `core_unix`.

It seems like `EINTR`'s are optionally [restarted](https://github.com/janestreet/core/blob/de2aea339e4b0ccaea30c78455e6641993234f01/src/core_unix.ml#L35) until successful, which is the default for [wait](https://github.com/janestreet/core/blob/de2aea339e4b0ccaea30c78455e6641993234f01/src/core_unix.ml#L966) calls. Maybe emulating this would fix this issue.
